export const Constants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_REQUEST_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_REQUEST_FAILURE',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',

    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_REQUEST_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_REQUEST_FAILURE',
};